/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    AdminDashboard: typeof import('./src/views/AdminDashboard.vue')['default']
    App: typeof import('./src/App.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ClientDashboard: typeof import('./src/views/ClientDashboard.vue')['default']
    Column: typeof import('primevue/column')['default']
    Dashboard: typeof import('./src/components/PortalClientes/dashboard.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Editor: typeof import('primevue/editor')['default']
    FormAgents: typeof import('./src/components/modules/modal/FormAgents.vue')['default']
    FormTickets: typeof import('./src/components/modules/modal/FormTickets.vue')['default']
    FormUsers: typeof import('./src/components/modules/modal/FormUsers.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    Hooks: typeof import('./src/hooks/principal.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    List: typeof import('./src/components/panelprincipal/list.vue')['default']
    Listatickets: typeof import('./src/components/modules/tickets/listatickets.vue')['default']
    Login: typeof import('./src/components/login/login.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Modal: typeof import('./src/components/modules/modal/modal.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Navbar: typeof import('./src/components/modules/menu/navbar.vue')['default']
    Panel: typeof import('./src/components/panelprincipal/panel.vue')['default']
    PanelPrincipal: typeof import('./src/components/panelprincipal/panelPrincipal.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    Principal: typeof import('./src/hooks/principal.vue')['default']
    Prueba: typeof import('./src/components/modules/modal/prueba.vue')['default']
    Prueba2: typeof import('./src/components/modules/tickets/prueba2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    TableAgents: typeof import('./src/components/modules/dataTables/tableAgents.vue')['default']
    TableTickets: typeof import('./src/components/modules/dataTables/tableTickets.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
